language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - npm install
  - bower install
  - grunt test
deploy:
  app: ng-obelisk
  provider: heroku
  api_key:
    secure: Pbup371Vt3S/5H41S90YWUp8skdgDZNHEnEUXKdWFGxe4/HHYHaOWdAXYsgHTMrAfOCFXaCieQ/sjFo/GD9Ra5Al67BUE3aFxB/N4LiQlQh6gtZwUCLIytzMlKbMOapfud97U2m0E+UlH+vJkCymSpSXi9gNlCAk6ylbQqLX+yo=